# .github/workflows/publish-release.yml
name: Publish release
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: ghalactic/github-release-from-tag@latest
